/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    courses: Course;
    'course-groups': CourseGroup;
    news: News;
    'success-stories': SuccessStory;
    staff: Staff;
    partners: Partner;
    media: Media;
    leads: Lead;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'course-groups': {
      courses: 'courses';
    };
  };
  collectionsSelect: {
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'course-groups': CourseGroupsSelect<false> | CourseGroupsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'success-stories': SuccessStoriesSelect<false> | SuccessStoriesSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ar' | 'he') | ('ar' | 'he')[];
  globals: {
    homepage: Homepage;
    'ui-texts': UiText;
    gallery: Gallery;
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'ui-texts': UiTextsSelect<false> | UiTextsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: 'ar' | 'he';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * كل دورات الكلية. لا يوجد حقل سعر — الأسعار لا تظهر على الموقع أبداً.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  name: string;
  group: number | CourseGroup;
  /**
   * سطرين تقريباً. يظهر على بطاقة الدورة في القوائم.
   */
  shortDescription: string;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * ماذا يتعلّم الطالب — كل موضوع بسطر.
   */
  topics?:
    | {
        topic: string;
        id?: string | null;
      }[]
    | null;
  /**
   * مثل: «تدريب عملي في ورشة مجهّزة». بدون أسعار وبدون وعود بالعمل.
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * مثال: «4 أشهر» / «4 חודשים».
   */
  duration?: string | null;
  /**
   * مجموع ساعات الدورة (رقم فقط).
   */
  hours?: number | null;
  /**
   * كم مرة يأتي الطالب (رقم فقط).
   */
  sessions?: number | null;
  schedule?: ('morning' | 'evening' | 'weekend' | 'online')[] | null;
  /**
   * مثال: «مرتين بالأسبوع، الأحد والثلاثاء 17:00–21:00».
   */
  scheduleDetails?: string | null;
  /**
   * اختياري. اتركه فارغاً إذا لم يُحدَّد بعد.
   */
  nextStart?: string | null;
  /**
   * بدل التاريخ أو معه، مثل: «التسجيل مفتوح — تبدأ الدورة عند اكتمال المجموعة».
   */
  nextStartNote?: string | null;
  /**
   * اسم الشهادة التي يحصل عليها الخريج.
   */
  certificate: string;
  /**
   * مثال: «وزارة العمل» / «משרד העבודה».
   */
  certifyingBody: string;
  /**
   * بدون وعود بالعمل. مثال: «تؤهّل للعمل كمساعد سلامة في مواقع البناء».
   */
  certificateValue?: string | null;
  admission?: {
    /**
     * مثال: «من جيل 18 وما فوق».
     */
    age?: string | null;
    /**
     * مثال: «10 سنوات تعليم».
     */
    education?: string | null;
    /**
     * مثال: «قراءة وكتابة أساسية».
     */
    hebrew?: string | null;
    experience?: string | null;
    other?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * عند التفعيل يظهر على الموقع النص الثابت: «الدورة ملائمة للحصول على منحة — تواصل معنا للاستشارة.» — هذا النص لا يُعدَّل.
   */
  voucherEligible?: boolean | null;
  /**
   * الصياغة المسموحة فقط: «مرافقة وتوجيه مهني بعد التخرّج» — مثل: توجيه عن سوق العمل، الشركات، والفرص. ممنوع: «ضمان تشغيل»، «شغل مضمون»، «بنشغّلك بعد الدورة»، «הבטחת תעסוקה». الموقع يعرض تلقائياً التنويه: «الكلية تقدّم مرافقة وتوجيه مهني، ولا تلتزم بتأمين مكان عمل.»
   */
  careerGuidance?: string | null;
  /**
   * تظهر على بطاقة الدورة وأعلى صفحتها. يُفضّل صورة حقيقية من الورشة.
   */
  coverImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  /**
   * فيديو قصير ومضغوط (أقل من دقيقة، MP4).
   */
  video?: (number | null) | Media;
  /**
   * تظهر قبل تشغيل الفيديو.
   */
  videoPoster?: (number | null) | Media;
  /**
   * بدل رفع الفيديو، يمكن وضع رابط فيديو من يوتيوب.
   */
  youtubeUrl?: string | null;
  /**
   * اختياري. إذا تركته فارغاً تُستعمل الإعدادات العامة للموقع.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  featured?: boolean | null;
  /**
   * الجزء الأخير من عنوان الصفحة على الإنترنت. إذا تركته فارغاً يُملأ تلقائياً من الاسم. لا تغيّره بعد النشر حتى لا تنكسر الروابط القديمة.
   */
  slug?: string | null;
  /**
   * الرقم الأصغر يظهر أولاً (1 قبل 2).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * مجالات الدورات (مثل: الحديد واللحام، البناء والسلامة، التكييف). كل دورة تابعة لمجال واحد. المجال بيظهر على الموقع بس إذا فيه دورة منشورة وحدة على الأقل.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-groups".
 */
export interface CourseGroup {
  id: number;
  name: string;
  /**
   * للأماكن الضيّقة. مثال: «اللحام» بدل «الحديد واللحام».
   */
  shortName?: string | null;
  /**
   * مثال: «مهنة مطلوبة في كل مصنع وورشة وموقع بناء».
   */
  tagline?: string | null;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * رمز صغير يظهر في الدائرة البيضاء (PNG شفّاف أو SVG).
   */
  icon?: (number | null) | Media;
  /**
   * الدورة بتنضاف للمجال من صفحة الدورة نفسها (خانة «المجال»).
   */
  courses?: {
    docs?: (number | Course)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * اختياري. إذا تركته فارغاً تُستعمل الإعدادات العامة للموقع.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * الجزء الأخير من عنوان الصفحة على الإنترنت. إذا تركته فارغاً يُملأ تلقائياً من الاسم. لا تغيّره بعد النشر حتى لا تنكسر الروابط القديمة.
   */
  slug?: string | null;
  /**
   * الرقم الأصغر يظهر أولاً (1 قبل 2).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 🎬 الفيديو: يجب أن يكون قصيراً (يُفضّل أقل من دقيقة) ومضغوطاً — بصيغة MP4، وحجمه أقل من 40 ميغابايت. الفيديو الكبير يجعل الموقع بطيئاً جداً على الموبايل. للضغط استعمل برنامجاً مجانياً مثل HandBrake (اختيار «Fast 1080p30») أو موقع freeconvert.com. 📷 الصور: JPG أو PNG أو WEBP، حتى 10 ميغابايت. الموقع يصغّرها تلقائياً.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * جملة قصيرة تصف ما يظهر (مثال: «طالب يتدرّب على اللحام في ورشة الكلية»). مهم لجوجل وللمكفوفين. اكتبها بالعربي وبالعبري.
   */
  alt: string;
  sourceFile?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  kind: 'news' | 'announcement' | 'event';
  publishedAt: string;
  pinned?: boolean | null;
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?: (number | Media)[] | null;
  relatedCourses?: (number | Course)[] | null;
  /**
   * اختياري. إذا تركته فارغاً تُستعمل الإعدادات العامة للموقع.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * الجزء الأخير من عنوان الصفحة على الإنترنت. إذا تركته فارغاً يُملأ تلقائياً من الاسم. لا تغيّره بعد النشر حتى لا تنكسر الروابط القديمة.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * خريجون حقيقيون — بموافقتهم على نشر الاسم والصورة والقصة. لا تنشر قصة لم يؤكّدها الخريج نفسه.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories".
 */
export interface SuccessStory {
  id: number;
  graduateName: string;
  course?: (number | null) | Course;
  graduationYear?: number | null;
  photo?: (number | null) | Media;
  /**
   * بدونه يظهر الخريج بالصورة والاسم فقط (بدون قصة).
   */
  quote?: string | null;
  /**
   * 2–3 جمل تظهر تحت الاقتباس في الصفحة الرئيسية.
   */
  excerpt?: string | null;
  /**
   * حقيقة عن الخريج فقط (مثال: «يعمل اليوم كلحّام في شركة بناء»). الصياغة المسموحة فقط: «مرافقة وتوجيه مهني بعد التخرّج» — مثل: توجيه عن سوق العمل، الشركات، والفرص. ممنوع: «ضمان تشغيل»، «شغل مضمون»، «بنشغّلك بعد الدورة»، «הבטחת תעסוקה». الموقع يعرض تلقائياً التنويه: «الكلية تقدّم مرافقة وتوجيه مهني، ولا تلتزم بتأمين مكان عمل.»
   */
  currentRole?: string | null;
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * فيديو قصير ومضغوط (أقل من دقيقة، MP4).
   */
  video?: (number | null) | Media;
  /**
   * مثال: 1:12
   */
  videoDuration?: string | null;
  featured?: boolean | null;
  /**
   * الجزء الأخير من عنوان الصفحة على الإنترنت. إذا تركته فارغاً يُملأ تلقائياً من الاسم. لا تغيّره بعد النشر حتى لا تنكسر الروابط القديمة.
   */
  slug?: string | null;
  /**
   * الرقم الأصغر يظهر أولاً (1 قبل 2).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  name: string;
  /**
   * مثال: «مركّز دورات اللحام».
   */
  role: string;
  /**
   * 3–4 جمل. تظهر مختصرة مع زر «اقرأ المزيد».
   */
  bio?: string | null;
  /**
   * صورة طولية (4:5)، الوجه واضح.
   */
  photo?: (number | null) | Media;
  slug?: string | null;
  /**
   * الرقم الأصغر يظهر أولاً (1 قبل 2).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * الجهات المعتمِدة والشركات الشريكة — لوغوهاتها تظهر في شريط «بالتعاون مع».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  /**
   * PNG شفّاف أو SVG، مقصوص بدون فراغ حوله.
   */
  logo: number | Media;
  url?: string | null;
  slug?: string | null;
  /**
   * الرقم الأصغر يظهر أولاً (1 قبل 2).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * كل من عبّأ استمارة «سجّل اهتمامك» في الموقع. بعد التواصل مع الشخص غيّر الحالة إلى «تمّ التواصل». يصل إيميل للكلية مع كل طلب جديد.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  course?: (number | null) | Course;
  courseOther?: string | null;
  message?: string | null;
  /**
   * بعد ما تحكي مع الشخص غيّرها لـ«تمّ التواصل» واضغط «حفظ». الرقم الأحمر بالقائمة بيعدّ الطلبات «الجديدة» بس.
   */
  status: 'new' | 'contacted' | 'closed';
  /**
   * لا يراها أحد خارج الكلية.
   */
  internalNotes?: string | null;
  locale?: ('ar' | 'he') | null;
  sourcePage?: string | null;
  website?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * من يستطيع الدخول للوحة التحكم. «مدير» يتحكم بكل شيء، «محرّر» يعدّل محتوى الموقع فقط (لا يرى الطلبات ولا المستخدمين). لتغيير كلمة السر تبعتك: اضغط على اسمك تحت بالقائمة الجانبية ← «تغيير كلمة المرور».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * اختار وحدة بس: «مدير» (كل إشي، مع الطلبات والحسابات) أو «محرّر» (نصوص وصور الموقع بس). إذا بدك تغيّرها، امسح القديمة بالـ ✕.
   */
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'course-groups';
        value: number | CourseGroup;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'success-stories';
        value: number | SuccessStory;
      } | null)
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  name?: T;
  group?: T;
  shortDescription?: T;
  fullDescription?: T;
  topics?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  duration?: T;
  hours?: T;
  sessions?: T;
  schedule?: T;
  scheduleDetails?: T;
  nextStart?: T;
  nextStartNote?: T;
  certificate?: T;
  certifyingBody?: T;
  certificateValue?: T;
  admission?:
    | T
    | {
        age?: T;
        education?: T;
        hebrew?: T;
        experience?: T;
        other?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  voucherEligible?: T;
  careerGuidance?: T;
  coverImage?: T;
  gallery?: T;
  video?: T;
  videoPoster?: T;
  youtubeUrl?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  featured?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-groups_select".
 */
export interface CourseGroupsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  tagline?: T;
  description?: T;
  image?: T;
  icon?: T;
  courses?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  publishedAt?: T;
  pinned?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  gallery?: T;
  relatedCourses?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories_select".
 */
export interface SuccessStoriesSelect<T extends boolean = true> {
  graduateName?: T;
  course?: T;
  graduationYear?: T;
  photo?: T;
  quote?: T;
  excerpt?: T;
  currentRole?: T;
  story?: T;
  video?: T;
  videoDuration?: T;
  featured?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  sourceFile?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  course?: T;
  courseOther?: T;
  message?: T;
  status?: T;
  internalNotes?: T;
  locale?: T;
  sourcePage?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * أقسام الصفحة الرئيسية من الأعلى للأسفل. اسحب القسم (⋮⋮) لتغيير ترتيبه، أو علّم «إخفاء هذا القسم مؤقتاً»، أو أضف قسماً جديداً من الزر في الأسفل.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  sections?:
    | (
        | HeroBlock
        | StatsBlock
        | CourseGroupsBlock
        | FeaturedCoursesBlock
        | WhyBlock
        | SuccessStoriesBlock
        | StaffBlock
        | VideosBlock
        | NewsBlock
        | PartnersBlock
        | EmployersBlock
        | FaqBlock
        | RegisterBlock
        | GalleryBlock
      )[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * يعمل تلقائياً بدون صوت ويتكرر. يجب أن يكون قصيراً جداً (10–30 ثانية) ومضغوطاً — أقل من 5 ميغابايت إن أمكن.
   */
  video?: (number | null) | Media;
  /**
   * تظهر قبل أن يبدأ الفيديو، وعلى الأجهزة التي لا تشغّل الفيديو. يُفضّل لقطة من نفس الفيديو.
   */
  poster?: (number | null) | Media;
  /**
   * مثال: «معتمدة من وزارة العمل · منذ 2008».
   */
  badge?: string | null;
  title: string;
  kicker?: string | null;
  text?: string | null;
  subtitle?: string | null;
  /**
   * مثال: «اللي بإيدو صنعة بملك قلعة».
   */
  slogan?: string | null;
  whatsappButton?: string | null;
  registerButton?: string | null;
  coursesLink?: string | null;
  scrollHint?: string | null;
  showGroupsStrip?: boolean | null;
  /**
   * تستعمله روابط القائمة (مثل #faq). لا تغيّره إلا إذا غيّرت رابط القائمة أيضاً.
   */
  anchor?: string | null;
  /**
   * القسم يبقى محفوظاً لكنه لا يظهر في الموقع.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  items?:
    | {
        value: number;
        suffix?: string | null;
        label: string;
        /**
         * مثال: courses
         */
        anchor?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * تستعمله روابط القائمة (مثل #faq). لا تغيّره إلا إذا غيّرت رابط القائمة أيضاً.
   */
  anchor?: string | null;
  /**
   * القسم يبقى محفوظاً لكنه لا يظهر في الموقع.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CourseGroupsBlock".
 */
export interface CourseGroupsBlock {
  kicker?: string | null;
  title: string;
  subtitle?: string | null;
  swipeHint?: string | null;
  /**
   * اتركه فارغاً لعرض كل المجموعات المنشورة حسب ترتيبها. أو اختر مجموعات معيّنة واسحبها لترتيبها.
   */
  groups?: (number | CourseGroup)[] | null;
  /**
   * تستعمله روابط القائمة (مثل #faq). لا تغيّره إلا إذا غيّرت رابط القائمة أيضاً.
   */
  anchor?: string | null;
  /**
   * القسم يبقى محفوظاً لكنه لا يظهر في الموقع.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'courseGroups';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCoursesBlock".
 */
export interface FeaturedCoursesBlock {
  kicker?: string | null;
  title: string;
  allCoursesButton?: string | null;
  /**
   * اتركه فارغاً لعرض الدورات المعلَّمة «دورة مميّزة» تلقائياً. أو اختر دورات معيّنة واسحبها لترتيبها.
   */
  courses?: (number | Course)[] | null;
  /**
   * تستعمله روابط القائمة (مثل #faq). لا تغيّره إلا إذا غيّرت رابط القائمة أيضاً.
   */
  anchor?: string | null;
  /**
   * القسم يبقى محفوظاً لكنه لا يظهر في الموقع.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredCourses';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyBlock".
 */
export interface WhyBlock {
  kicker?: string | null;
  title: string;
  items?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  pills?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * مثال: 2008
   */
  badgeNumber?: string | null;
  badgeText?: string | null;
  /**
   * تستعمله روابط القائمة (مثل #faq). لا تغيّره إلا إذا غيّرت رابط القائمة أيضاً.
   */
  anchor?: string | null;
  /**
   * القسم يبقى محفوظاً لكنه لا يظهر في الموقع.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'why';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SuccessStoriesBlock".
 */
export interface SuccessStoriesBlock {
  kicker?: string | null;
  title: string;
  subtitle?: string | null;
  /**
   * مثال: «فيديو قصة النجاح».
   */
  videoLabel?: string | null;
  /**
   * اتركه فارغاً لعرض القصص المعلَّمة «تظهر في الصفحة الرئيسية». تظهر فقط القصص التي فيها اقتباس.
   */
  stories?: (number | SuccessStory)[] | null;
  rotateSeconds?: number | null;
  /**
   * تستعمله روابط القائمة (مثل #faq). لا تغيّره إلا إذا غيّرت رابط القائمة أيضاً.
   */
  anchor?: string | null;
  /**
   * القسم يبقى محفوظاً لكنه لا يظهر في الموقع.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'successStories';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StaffBlock".
 */
export interface StaffBlock {
  kicker?: string | null;
  title: string;
  subtitle?: string | null;
  /**
   * اتركه فارغاً لعرض كل الطاقم حسب الترتيب.
   */
  members?: (number | Staff)[] | null;
  /**
   * تستعمله روابط القائمة (مثل #faq). لا تغيّره إلا إذا غيّرت رابط القائمة أيضاً.
   */
  anchor?: string | null;
  /**
   * القسم يبقى محفوظاً لكنه لا يظهر في الموقع.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'staff';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideosBlock".
 */
export interface VideosBlock {
  kicker?: string | null;
  title: string;
  subtitle?: string | null;
  promo?: {
    /**
     * يُفضّل دقيقة واحدة تقريباً، MP4 مضغوط، أقل من 40 ميغابايت.
     */
    video?: (number | null) | Media;
    youtubeUrl?: string | null;
    /**
     * تظهر قبل الضغط على «تشغيل».
     */
    poster?: (number | null) | Media;
    /**
     * مثال: 1:00
     */
    durationLabel?: string | null;
    /**
     * مثال: «إعلان تعريفي».
     */
    kind?: string | null;
    title?: string | null;
    subtitle?: string | null;
    playLabel?: string | null;
  };
  reels?:
    | {
        title: string;
        poster?: (number | null) | Media;
        /**
         * فيديو طولي قصير (15–30 ثانية)، MP4 مضغوط.
         */
        video?: (number | null) | Media;
        /**
         * مثال: 0:20
         */
        durationLabel?: string | null;
        /**
         * زر «تفاصيل الدورة» يفتح واتساب باسم هذه الدورة.
         */
        course?: (number | null) | Course;
        id?: string | null;
      }[]
    | null;
  /**
   * اسم الدورة يُضاف بعدها تلقائياً. مثال: «مرحبا، بدي تفاصيل عن: ».
   */
  whatsappMessage?: string | null;
  swipeHint?: string | null;
  /**
   * تستعمله روابط القائمة (مثل #faq). لا تغيّره إلا إذا غيّرت رابط القائمة أيضاً.
   */
  anchor?: string | null;
  /**
   * القسم يبقى محفوظاً لكنه لا يظهر في الموقع.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsBlock".
 */
export interface NewsBlock {
  kicker?: string | null;
  title: string;
  /**
   * تظهر آخر الأخبار المنشورة تلقائياً (المثبّتة أولاً).
   */
  count?: number | null;
  /**
   * تستعمله روابط القائمة (مثل #faq). لا تغيّره إلا إذا غيّرت رابط القائمة أيضاً.
   */
  anchor?: string | null;
  /**
   * القسم يبقى محفوظاً لكنه لا يظهر في الموقع.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'news';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock".
 */
export interface PartnersBlock {
  title: string;
  /**
   * اتركه فارغاً لعرض كل الشركاء حسب الترتيب.
   */
  partners?: (number | Partner)[] | null;
  /**
   * تستعمله روابط القائمة (مثل #faq). لا تغيّره إلا إذا غيّرت رابط القائمة أيضاً.
   */
  anchor?: string | null;
  /**
   * القسم يبقى محفوظاً لكنه لا يظهر في الموقع.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partners';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmployersBlock".
 */
export interface EmployersBlock {
  kicker?: string | null;
  title: string;
  text?: string | null;
  items?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  whatsappButton?: string | null;
  hiringButton?: string | null;
  /**
   * بدون وعود. مثال: «الكلية على تواصل دائم مع خريجيها. تواصل معنا ونوجّه إليك خريجين ملائمين.»
   */
  hiringText?: string | null;
  /**
   * تستعمله روابط القائمة (مثل #faq). لا تغيّره إلا إذا غيّرت رابط القائمة أيضاً.
   */
  anchor?: string | null;
  /**
   * القسم يبقى محفوظاً لكنه لا يظهر في الموقع.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'employers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  kicker?: string | null;
  title: string;
  text?: string | null;
  /**
   * عند الحديث عن ما بعد التخرّج: الصياغة المسموحة فقط: «مرافقة وتوجيه مهني بعد التخرّج» — مثل: توجيه عن سوق العمل، الشركات، والفرص. ممنوع: «ضمان تشغيل»، «شغل مضمون»، «بنشغّلك بعد الدورة»، «הבטחת תעסוקה». الموقع يعرض تلقائياً التنويه: «الكلية تقدّم مرافقة وتوجيه مهني، ولا تلتزم بتأمين مكان عمل.»
   */
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * تستعمله روابط القائمة (مثل #faq). لا تغيّره إلا إذا غيّرت رابط القائمة أيضاً.
   */
  anchor?: string | null;
  /**
   * القسم يبقى محفوظاً لكنه لا يظهر في الموقع.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RegisterBlock".
 */
export interface RegisterBlock {
  kicker?: string | null;
  title: string;
  text?: string | null;
  /**
   * نص ثابت لا يُعدَّل: «الدورة ملائمة للحصول على منحة — تواصل معنا للاستشارة.»
   */
  showVoucherNote?: boolean | null;
  bullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * رقم الواتساب يُضاف تلقائياً من «إعدادات الموقع».
   */
  whatsappButton?: string | null;
  /**
   * تستعمله روابط القائمة (مثل #faq). لا تغيّره إلا إذا غيّرت رابط القائمة أيضاً.
   */
  anchor?: string | null;
  /**
   * القسم يبقى محفوظاً لكنه لا يظهر في الموقع.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'register';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  kicker?: string | null;
  title: string;
  subtitle?: string | null;
  /**
   * الصور تُؤخذ من صفحة «معرض الصور والفيديو» بنفس الترتيب.
   */
  count?: number | null;
  /**
   * تستعمله روابط القائمة (مثل #faq). لا تغيّره إلا إذا غيّرت رابط القائمة أيضاً.
   */
  anchor?: string | null;
  /**
   * القسم يبقى محفوظاً لكنه لا يظهر في الموقع.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * كلمات وأزرار تتكرر في كل الموقع: القائمة، الأزرار، الاستمارة… غيّر النص هنا فيتغيّر في كل مكان. نص المنحة وتنبيه التشغيل ثابتان ولا يُعدَّلان (قواعد الكلية).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-texts".
 */
export interface UiText {
  id: number;
  /**
   * يظهر في النسخة العربية «עברית»، وفي العبرية «العربية».
   */
  otherLang?: string | null;
  a11y?: string | null;
  nav?: {
    home?: string | null;
    courses?: string | null;
    allCourses?: string | null;
    about?: string | null;
    graduates?: string | null;
    gallery?: string | null;
    news?: string | null;
    employers?: string | null;
    contact?: string | null;
    faq?: string | null;
    staff?: string | null;
    menu?: string | null;
    close?: string | null;
  };
  pageTitles?: {
    graduatesTitle?: string | null;
  };
  common?: {
    readMore?: string | null;
    viewCourse?: string | null;
    allCourses?: string | null;
    contactUs?: string | null;
    whatsapp?: string | null;
    whatsappLong?: string | null;
    whatsappContact?: string | null;
    call?: string | null;
    registerInterest?: string | null;
    hours?: string | null;
    sessions?: string | null;
    courseCount?: string | null;
    /**
     * مثال: «مسائي · 17:00–21:00».
     */
    evening?: string | null;
    nextStart?: string | null;
    swipe?: string | null;
  };
  /**
   * تستعملها صفحات الموقع الداخلية. أرقام الصفحة الرئيسية تُعدَّل من قسم «أرقام».
   */
  stats?: {
    years?: string | null;
    courses?: string | null;
    groups?: string | null;
    partners?: string | null;
    graduates?: string | null;
    alumni?: string | null;
  };
  /**
   * جمل قصيرة تظهر في أكثر من مكان (مثل: «منذ 2008»، «بإشراف وزارة العمل»).
   */
  trust?:
    | {
        title?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  form?: {
    name?: string | null;
    phone?: string | null;
    email?: string | null;
    course?: string | null;
    courseSelect?: string | null;
    courseAny?: string | null;
    message?: string | null;
    submit?: string | null;
    privacy?: string | null;
    successTitle?: string | null;
    successText?: string | null;
    error?: string | null;
  };
  course?: {
    /**
     * بدون أرقام وبدون أسعار — الأسعار لا تُعرض أبداً.
     */
    contactForPrice?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * صور حقيقية من الورشات والتدريبات، وفيديوهات يوتيوب. اسحب لتغيير الترتيب.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title?: string | null;
  intro?: string | null;
  images?: (number | Media)[] | null;
  videos?:
    | {
        title: string;
        /**
         * مثال: https://www.youtube.com/watch?v=c3PP4-TM3Y0
         */
        youtubeUrl?: string | null;
        file?: (number | null) | Media;
        thumbnail?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * اللوغو، معلومات الاتصال، السوشال ميديا، وإعدادات جوجل — تظهر في كل صفحات الموقع.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * مثال: «كلية المركز».
   */
  shortName?: string | null;
  tagline?: string | null;
  city?: string | null;
  /**
   * مثال: «بإشراف وزارة العمل منذ 2008».
   */
  accreditation?: string | null;
  foundedYear?: number | null;
  /**
   * النسخة الملوّنة/الغامقة التي تظهر على خلفية بيضاء. يُفضّل SVG أو PNG شفّاف.
   */
  logoLight?: (number | null) | Media;
  /**
   * النسخة البيضاء/الفاتحة التي تظهر فوق الفيديو أو الخلفيات الغامقة.
   */
  logoDark?: (number | null) | Media;
  /**
   * الرمز بدون الكتابة — للموبايل والأماكن الضيّقة.
   */
  logoMark?: (number | null) | Media;
  /**
   * الصورة الصغيرة في تبويب المتصفح. مربّعة، 512×512 بكسل، PNG.
   */
  favicon?: (number | null) | Media;
  contact?: {
    phones?:
      | {
          /**
           * مثال: «المكتب»، «التسجيل».
           */
          label?: string | null;
          /**
           * مثال: 04-6111111
           */
          number: string;
          showInHeader?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * بالصيغة الدولية بدون + وبدون صفر البداية. مثال: 972501234567
     */
    whatsapp?: string | null;
    /**
     * مثال: «مرحباً، بدي أستفسر عن الدورات».
     */
    whatsappMessage?: string | null;
    email?: string | null;
    address?: string | null;
    /**
     * الرابط الذي يفتح الخريطة عند الضغط.
     */
    mapUrl?: string | null;
    /**
     * من Google Maps: مشاركة ← تضمين خريطة ← انسخ الرابط الذي داخل src="..." فقط.
     */
    mapEmbedUrl?: string | null;
    openingHours?:
      | {
          /**
           * مثال: «الأحد – الخميس».
           */
          days: string;
          /**
           * مثال: «08:00 – 16:00» أو «مغلق».
           */
          hours: string;
          id?: string | null;
        }[]
      | null;
  };
  social?:
    | {
        platform: 'facebook' | 'instagram' | 'tiktok' | 'youtube' | 'linkedin' | 'x' | 'telegram' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * %s تُستبدل باسم الصفحة. مثال: «%s | كلية المركز للتأهيل المهني».
     */
    titleTemplate?: string | null;
    defaultTitle?: string | null;
    defaultDescription?: string | null;
    /**
     * تظهر عند مشاركة رابط الموقع في واتساب وفيسبوك. 1200×630 بكسل.
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * كل طلب «سجّل اهتمامك» جديد يُرسَل لهذه العناوين. إذا تُركت فارغة يُرسَل للإيميل في تبويب «الاتصال».
   */
  leadsNotificationEmails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * قائمة أعلى الموقع، وأسفل الموقع (التذييل). اسحب العناصر لتغيير ترتيبها.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?: {
    items?:
      | {
          label: string;
          link?: {
            type?: ('anchor' | 'page' | 'course' | 'courseGroup' | 'whatsapp' | 'phone' | 'external') | null;
            page?:
              | (
                  | 'home'
                  | 'courses'
                  | 'about'
                  | 'gallery'
                  | 'success-stories'
                  | 'news'
                  | 'companies'
                  | 'contact'
                  | 'staff'
                  | 'faq'
                  | 'register'
                  | 'accessibility'
                )
              | null;
            /**
             * نفس «اسم القسم في الرابط» في الصفحة الرئيسية. مثال: fields ، why ، graduates ، video ، news ، employers ، faq ، register
             */
            anchor?: string | null;
            course?: (number | null) | Course;
            courseGroup?: (number | null) | CourseGroup;
            /**
             * مثال: https://www.facebook.com/...
             */
            url?: string | null;
            /**
             * النص الذي يظهر جاهزاً عند فتح الواتساب. إذا تركته فارغاً تُستعمل الرسالة العامة من «إعدادات الموقع».
             */
            whatsappMessage?: string | null;
            newTab?: boolean | null;
          };
          children?:
            | {
                label: string;
                link?: {
                  type?: ('anchor' | 'page' | 'course' | 'courseGroup' | 'whatsapp' | 'phone' | 'external') | null;
                  page?:
                    | (
                        | 'home'
                        | 'courses'
                        | 'about'
                        | 'gallery'
                        | 'success-stories'
                        | 'news'
                        | 'companies'
                        | 'contact'
                        | 'staff'
                        | 'faq'
                        | 'register'
                        | 'accessibility'
                      )
                    | null;
                  /**
                   * نفس «اسم القسم في الرابط» في الصفحة الرئيسية. مثال: fields ، why ، graduates ، video ، news ، employers ، faq ، register
                   */
                  anchor?: string | null;
                  course?: (number | null) | Course;
                  courseGroup?: (number | null) | CourseGroup;
                  /**
                   * مثال: https://www.facebook.com/...
                   */
                  url?: string | null;
                  /**
                   * النص الذي يظهر جاهزاً عند فتح الواتساب. إذا تركته فارغاً تُستعمل الرسالة العامة من «إعدادات الموقع».
                   */
                  whatsappMessage?: string | null;
                  newTab?: boolean | null;
                };
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    cta?: {
      show?: boolean | null;
      label?: string | null;
      link?: {
        type?: ('anchor' | 'page' | 'course' | 'courseGroup' | 'whatsapp' | 'phone' | 'external') | null;
        page?:
          | (
              | 'home'
              | 'courses'
              | 'about'
              | 'gallery'
              | 'success-stories'
              | 'news'
              | 'companies'
              | 'contact'
              | 'staff'
              | 'faq'
              | 'register'
              | 'accessibility'
            )
          | null;
        /**
         * نفس «اسم القسم في الرابط» في الصفحة الرئيسية. مثال: fields ، why ، graduates ، video ، news ، employers ، faq ، register
         */
        anchor?: string | null;
        course?: (number | null) | Course;
        courseGroup?: (number | null) | CourseGroup;
        /**
         * مثال: https://www.facebook.com/...
         */
        url?: string | null;
        /**
         * النص الذي يظهر جاهزاً عند فتح الواتساب. إذا تركته فارغاً تُستعمل الرسالة العامة من «إعدادات الموقع».
         */
        whatsappMessage?: string | null;
        newTab?: boolean | null;
      };
    };
  };
  footer?: {
    about?: string | null;
    columns?:
      | {
          title: string;
          links?:
            | {
                label: string;
                link?: {
                  type?: ('anchor' | 'page' | 'course' | 'courseGroup' | 'whatsapp' | 'phone' | 'external') | null;
                  page?:
                    | (
                        | 'home'
                        | 'courses'
                        | 'about'
                        | 'gallery'
                        | 'success-stories'
                        | 'news'
                        | 'companies'
                        | 'contact'
                        | 'staff'
                        | 'faq'
                        | 'register'
                        | 'accessibility'
                      )
                    | null;
                  /**
                   * نفس «اسم القسم في الرابط» في الصفحة الرئيسية. مثال: fields ، why ، graduates ، video ، news ، employers ، faq ، register
                   */
                  anchor?: string | null;
                  course?: (number | null) | Course;
                  courseGroup?: (number | null) | CourseGroup;
                  /**
                   * مثال: https://www.facebook.com/...
                   */
                  url?: string | null;
                  /**
                   * النص الذي يظهر جاهزاً عند فتح الواتساب. إذا تركته فارغاً تُستعمل الرسالة العامة من «إعدادات الموقع».
                   */
                  whatsappMessage?: string | null;
                  newTab?: boolean | null;
                };
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    /**
     * العنوان والهواتف والإيميل تُؤخذ من «إعدادات الموقع».
     */
    contactTitle?: string | null;
    /**
     * {year} تُستبدل بالسنة الحالية تلقائياً. مثال: «© {year} كلية المركز. جميع الحقوق محفوظة.»
     */
    copyright?: string | null;
    /**
     * مثل: سياسة الخصوصية، إمكانية الوصول (נגישות).
     */
    bottomLinks?:
      | {
          label: string;
          link?: {
            type?: ('anchor' | 'page' | 'course' | 'courseGroup' | 'whatsapp' | 'phone' | 'external') | null;
            page?:
              | (
                  | 'home'
                  | 'courses'
                  | 'about'
                  | 'gallery'
                  | 'success-stories'
                  | 'news'
                  | 'companies'
                  | 'contact'
                  | 'staff'
                  | 'faq'
                  | 'register'
                  | 'accessibility'
                )
              | null;
            /**
             * نفس «اسم القسم في الرابط» في الصفحة الرئيسية. مثال: fields ، why ، graduates ، video ، news ، employers ، faq ، register
             */
            anchor?: string | null;
            course?: (number | null) | Course;
            courseGroup?: (number | null) | CourseGroup;
            /**
             * مثال: https://www.facebook.com/...
             */
            url?: string | null;
            /**
             * النص الذي يظهر جاهزاً عند فتح الواتساب. إذا تركته فارغاً تُستعمل الرسالة العامة من «إعدادات الموقع».
             */
            whatsappMessage?: string | null;
            newTab?: boolean | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        courseGroups?: T | CourseGroupsBlockSelect<T>;
        featuredCourses?: T | FeaturedCoursesBlockSelect<T>;
        why?: T | WhyBlockSelect<T>;
        successStories?: T | SuccessStoriesBlockSelect<T>;
        staff?: T | StaffBlockSelect<T>;
        videos?: T | VideosBlockSelect<T>;
        news?: T | NewsBlockSelect<T>;
        partners?: T | PartnersBlockSelect<T>;
        employers?: T | EmployersBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        register?: T | RegisterBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  video?: T;
  poster?: T;
  badge?: T;
  title?: T;
  kicker?: T;
  text?: T;
  subtitle?: T;
  slogan?: T;
  whatsappButton?: T;
  registerButton?: T;
  coursesLink?: T;
  scrollHint?: T;
  showGroupsStrip?: T;
  anchor?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        anchor?: T;
        id?: T;
      };
  anchor?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CourseGroupsBlock_select".
 */
export interface CourseGroupsBlockSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  subtitle?: T;
  swipeHint?: T;
  groups?: T;
  anchor?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCoursesBlock_select".
 */
export interface FeaturedCoursesBlockSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  allCoursesButton?: T;
  courses?: T;
  anchor?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyBlock_select".
 */
export interface WhyBlockSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  items?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  image?: T;
  pills?:
    | T
    | {
        text?: T;
        id?: T;
      };
  badgeNumber?: T;
  badgeText?: T;
  anchor?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SuccessStoriesBlock_select".
 */
export interface SuccessStoriesBlockSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  subtitle?: T;
  videoLabel?: T;
  stories?: T;
  rotateSeconds?: T;
  anchor?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StaffBlock_select".
 */
export interface StaffBlockSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  subtitle?: T;
  members?: T;
  anchor?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideosBlock_select".
 */
export interface VideosBlockSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  subtitle?: T;
  promo?:
    | T
    | {
        video?: T;
        youtubeUrl?: T;
        poster?: T;
        durationLabel?: T;
        kind?: T;
        title?: T;
        subtitle?: T;
        playLabel?: T;
      };
  reels?:
    | T
    | {
        title?: T;
        poster?: T;
        video?: T;
        durationLabel?: T;
        course?: T;
        id?: T;
      };
  whatsappMessage?: T;
  swipeHint?: T;
  anchor?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsBlock_select".
 */
export interface NewsBlockSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  count?: T;
  anchor?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock_select".
 */
export interface PartnersBlockSelect<T extends boolean = true> {
  title?: T;
  partners?: T;
  anchor?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmployersBlock_select".
 */
export interface EmployersBlockSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  text?: T;
  items?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  whatsappButton?: T;
  hiringButton?: T;
  hiringText?: T;
  anchor?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  text?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  anchor?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RegisterBlock_select".
 */
export interface RegisterBlockSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  text?: T;
  showVoucherNote?: T;
  bullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  whatsappButton?: T;
  anchor?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  subtitle?: T;
  count?: T;
  anchor?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-texts_select".
 */
export interface UiTextsSelect<T extends boolean = true> {
  otherLang?: T;
  a11y?: T;
  nav?:
    | T
    | {
        home?: T;
        courses?: T;
        allCourses?: T;
        about?: T;
        graduates?: T;
        gallery?: T;
        news?: T;
        employers?: T;
        contact?: T;
        faq?: T;
        staff?: T;
        menu?: T;
        close?: T;
      };
  pageTitles?:
    | T
    | {
        graduatesTitle?: T;
      };
  common?:
    | T
    | {
        readMore?: T;
        viewCourse?: T;
        allCourses?: T;
        contactUs?: T;
        whatsapp?: T;
        whatsappLong?: T;
        whatsappContact?: T;
        call?: T;
        registerInterest?: T;
        hours?: T;
        sessions?: T;
        courseCount?: T;
        evening?: T;
        nextStart?: T;
        swipe?: T;
      };
  stats?:
    | T
    | {
        years?: T;
        courses?: T;
        groups?: T;
        partners?: T;
        graduates?: T;
        alumni?: T;
      };
  trust?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  form?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
        course?: T;
        courseSelect?: T;
        courseAny?: T;
        message?: T;
        submit?: T;
        privacy?: T;
        successTitle?: T;
        successText?: T;
        error?: T;
      };
  course?:
    | T
    | {
        contactForPrice?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  images?: T;
  videos?:
    | T
    | {
        title?: T;
        youtubeUrl?: T;
        file?: T;
        thumbnail?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  shortName?: T;
  tagline?: T;
  city?: T;
  accreditation?: T;
  foundedYear?: T;
  logoLight?: T;
  logoDark?: T;
  logoMark?: T;
  favicon?: T;
  contact?:
    | T
    | {
        phones?:
          | T
          | {
              label?: T;
              number?: T;
              showInHeader?: T;
              id?: T;
            };
        whatsapp?: T;
        whatsappMessage?: T;
        email?: T;
        address?: T;
        mapUrl?: T;
        mapEmbedUrl?: T;
        openingHours?:
          | T
          | {
              days?: T;
              hours?: T;
              id?: T;
            };
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        titleTemplate?: T;
        defaultTitle?: T;
        defaultDescription?: T;
        ogImage?: T;
      };
  leadsNotificationEmails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        items?:
          | T
          | {
              label?: T;
              link?:
                | T
                | {
                    type?: T;
                    page?: T;
                    anchor?: T;
                    course?: T;
                    courseGroup?: T;
                    url?: T;
                    whatsappMessage?: T;
                    newTab?: T;
                  };
              children?:
                | T
                | {
                    label?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          page?: T;
                          anchor?: T;
                          course?: T;
                          courseGroup?: T;
                          url?: T;
                          whatsappMessage?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        cta?:
          | T
          | {
              show?: T;
              label?: T;
              link?:
                | T
                | {
                    type?: T;
                    page?: T;
                    anchor?: T;
                    course?: T;
                    courseGroup?: T;
                    url?: T;
                    whatsappMessage?: T;
                    newTab?: T;
                  };
            };
      };
  footer?:
    | T
    | {
        about?: T;
        columns?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    label?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          page?: T;
                          anchor?: T;
                          course?: T;
                          courseGroup?: T;
                          url?: T;
                          whatsappMessage?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        contactTitle?: T;
        copyright?: T;
        bottomLinks?:
          | T
          | {
              label?: T;
              link?:
                | T
                | {
                    type?: T;
                    page?: T;
                    anchor?: T;
                    course?: T;
                    courseGroup?: T;
                    url?: T;
                    whatsappMessage?: T;
                    newTab?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'news';
      value: number | News;
    } | null;
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}